export const authTypes = {
  DO_SIGN_IN: "auth/DO_SIGN_IN",
  DO_SIGN_OUT: "auth/DO_SIGN_OUT",
  REGISTER_COMPLETED: "auth/REGISTER_COMPLETED",
  REGISTER_ERROR: "auth/REGISTER_ERROR",
  SIGN_IN_SUCCESS: "auth/SIGNIN_SUCCESS",
  SIGN_IN_ERROR: "auth/SIGNIN_ERROR",
};
